<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PocketTX.Companion.Core\PocketTX.Companion.Core.csproj" />
    <ProjectReference Include="..\PocketTX.Companion.Shared\PocketTX.Companion.Shared.csproj" />
    <ProjectReference Include="..\PocketTX.Companion.Protocol\PocketTX.Companion.Protocol.csproj" />
    <ProjectReference Include="..\PocketTX.Companion.VirtualController\PocketTX.Companion.VirtualController.csproj" />
    <ProjectReference Include="..\PocketTX.Companion.Logging\PocketTX.Companion.Logging.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
