<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PocketTX.Companion.Core\PocketTX.Companion.Core.csproj" />
    <ProjectReference Include="..\PocketTX.Companion.Shared\PocketTX.Companion.Shared.csproj" />
    <ProjectReference Include="..\PocketTX.Companion.Protocol\PocketTX.Companion.Protocol.csproj" />
    <ProjectReference Include="..\PocketTX.Companion.VirtualController\PocketTX.Companion.VirtualController.csproj" />
    <ProjectReference Include="..\PocketTX.Companion.Logging\PocketTX.Companion.Logging.csproj" />
    <ProjectReference Include="..\PocketTX.Companion.Services\PocketTX.Companion.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
